// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn3onypISb_wd_PCVIIkmBheqAczRHq1Y',
    appId: '1:828515421950:web:fec86dca4b5dfc809e9faf',
    messagingSenderId: '828515421950',
    projectId: 'interactive-calendar-eba76',
    authDomain: 'interactive-calendar-eba76.firebaseapp.com',
    storageBucket: 'interactive-calendar-eba76.firebasestorage.app',
    measurementId: 'G-37F51YGV53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQS8iq27dQ5e3BO7nU_JoinTzeB6_i66Q',
    appId: '1:828515421950:android:6bc2118b6f29e56e9e9faf',
    messagingSenderId: '828515421950',
    projectId: 'interactive-calendar-eba76',
    storageBucket: 'interactive-calendar-eba76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlOKR1O2VEKQd1Ri9vwDeEroM-pPUuUlw',
    appId: '1:828515421950:ios:ac614c72b657ec319e9faf',
    messagingSenderId: '828515421950',
    projectId: 'interactive-calendar-eba76',
    storageBucket: 'interactive-calendar-eba76.firebasestorage.app',
    iosBundleId: 'com.example.interactiveCalendar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlOKR1O2VEKQd1Ri9vwDeEroM-pPUuUlw',
    appId: '1:828515421950:ios:ac614c72b657ec319e9faf',
    messagingSenderId: '828515421950',
    projectId: 'interactive-calendar-eba76',
    storageBucket: 'interactive-calendar-eba76.firebasestorage.app',
    iosBundleId: 'com.example.interactiveCalendar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn3onypISb_wd_PCVIIkmBheqAczRHq1Y',
    appId: '1:828515421950:web:b4c5c2ee3ac300a89e9faf',
    messagingSenderId: '828515421950',
    projectId: 'interactive-calendar-eba76',
    authDomain: 'interactive-calendar-eba76.firebaseapp.com',
    storageBucket: 'interactive-calendar-eba76.firebasestorage.app',
    measurementId: 'G-1T6PG4JM5T',
  );
}
